spring:
  application:
    name: api
  datasource:
#    url: jdbc:mysql://soknem.rwlb.eu-west-1.rds.aliyuncs.com:3306/api
#    username: soknem
#    password: soknem@123
    url: jdbc:mysql://localhost:3306/api
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

server.port: 8081

ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key

logging:
  level:
    root: INFO
    web: DEBUG
    org.springframework.security: DEBUG  # Logs Spring Security details
    org.springframework.web: DEBUG       # Logs web requests
    org.hibernate.SQL: DEBUG             # Logs SQL queries
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE